package com.bawei.shenmengkai.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bawei.shenmengkai.bean.GreenDaoJson;

import com.bawei.shenmengkai.dao.GreenDaoJsonDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig greenDaoJsonDaoConfig;

    private final GreenDaoJsonDao greenDaoJsonDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        greenDaoJsonDaoConfig = daoConfigMap.get(GreenDaoJsonDao.class).clone();
        greenDaoJsonDaoConfig.initIdentityScope(type);

        greenDaoJsonDao = new GreenDaoJsonDao(greenDaoJsonDaoConfig, this);

        registerDao(GreenDaoJson.class, greenDaoJsonDao);
    }
    
    public void clear() {
        greenDaoJsonDaoConfig.clearIdentityScope();
    }

    public GreenDaoJsonDao getGreenDaoJsonDao() {
        return greenDaoJsonDao;
    }

}
